apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  labels:
    type: local
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"