apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj11/frontend:1.0
        name: frontend
        env:
          - name: API_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: frontend-cmap
                key: API_ADDRESS
          - name: EXCHANGE_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: frontend-cmap
                key: EXCHANGE_SERVICE_ADDRESS
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: frontend-cmap
                key: PORT