# Generated by Django 4.0.1 on 2022-01-20 21:25

from django.db import migrations, models
import oferty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=1000)),
                ('price', models.FloatField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('upload', models.ImageField(blank=True, null=True, upload_to=oferty.models.upload_path)),
            ],
        ),
    ]
