# Generated by Django 4.0.1 on 2022-01-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
